driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/occi-server']

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.0

platforms:
  - name: ubuntu-16.04
    run_list: apt::default
  - name: centos-7
    run_list: yum-epel::default

suites:
  - name: default
    run_list:
      - omnibus::default
      - omnibus-build::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/occi-server
        install_dir: /opt/occi-server
