#!/bin/bash
#
# Install the occi-server
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/occi-server
CONFIG_DIR=/etc/occi-server
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Could not remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Could not create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Could not install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

exit 0
