#!/bin/bash
#
# Install the occi-server
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/occi-server
CONFIG_DIR=/etc/occi-server
LOG_DIR=/var/log/occi-server
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Could not remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Could not create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Could not install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

# chown
chown -R root:root $DEST_DIR || error_exit "Could not chown $DEST_DIR to root:root"

# prepare dir structure
mkdir -p $CONFIG_DIR || error_exit "Could not create $CONFIG_DIR"
mkdir -p $LOG_DIR || error_exit "Could not create $LOG_DIR"

# create the rocci user
id -u rocci
if [ "$?" -ne "0" ]; then
  useradd --system --shell /bin/false rocci || error_exit "Could not create the rocci user account"
  usermod -L rocci || error_exit "Could not lock the rocci user account"
fi

# chown log dir
chown -R rocci:rocci $LOG_DIR || error_exit "Could not chown $LOG_DIR to rocci:rocci"

exit 0
