#!/bin/bash
#
# Perform necessary occi-server removal steps
# after package is uninstalled.
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
USAGE="usage: $0"

DEST_DIR="/opt/occi-server"
CONFIG_DIR="/etc/occi-server"
CONFIG_FILE="${CONFIG_DIR}/rocci_server.yml"
LOG_DIR="/var/log/occi-server"
SYSD_DIR="/etc/systemd/system"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ "X$1" = "purge" ] || [ "X$1" = "X0" ]; then
  if [ -d "$CONFIG_DIR" ]; then
    rm -rf "$CONFIG_DIR" || error_exit "Could not unlink $CONFIG_DIR"
  fi

  if [ -d "$LOG_DIR" ]; then
    rm -rf "$LOG_DIR" || error_exit "Could not unlink $LOG_DIR"
  fi

  if [ -d "$DEST_DIR" ]; then
    rm -rf "$DEST_DIR" || error_exit "Could not unlink $DEST_DIR"
  fi

  for SD_FILE in ${SYSD_DIR}/occi-server.* ; do
    if [ -f "$SD_FILE" ] && [ -L "$SD_FILE" ]; then
      rm "$SD_FILE" || error_exit "Could not unlink $SD_FILE"
    fi
  done
fi

echo "occi-server has been uninstalled!"

exit 0
