#!/bin/bash
#
# Perform necessary occi-server setup steps
# after package is installed.
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
USAGE="usage: $0"

DEST_DIR="/opt/occi-server"
CONFIG_DIR="/etc/occi-server"
CONFIG_FILE="${CONFIG_DIR}/rocci_server.yml"
LOG_DIR="/var/log/occi-server"
SYSD_DIR="/etc/systemd/system"

EMB_DEST_DIR="${DEST_DIR}/embedded/app/rOCCI-server"
EMB_CONFIG_FILE="${EMB_DEST_DIR}/config/rocci_server.yml"
EMB_LOG_DIR="${EMB_DEST_DIR}/log"
EMB_SYSD_DIR="${EMB_DEST_DIR}/examples/systemd"

DEFAULT_BACKEND="opennebula"
DEFAULT_PORT=11443

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# installation ownership
chown -R root:root $DEST_DIR || error_exit "Could not chown $DEST_DIR to root:root"

# user
id -u rocci > /dev/null 2>&1
if [ "$?" -ne "0" ]; then
  useradd --system --shell /bin/false rocci || error_exit "Could not create the rocci user account"
  usermod -L rocci || error_exit "Could not lock the rocci user account"
fi

# logging
if [ ! -d "$LOG_DIR" ]; then
  mkdir -p "$LOG_DIR" || error_exit "Could not create $LOG_DIR"
  chown rocci:rocci "$LOG_DIR" || error_exit "Could not change ownership of $LOG_DIR"
fi

if [ ! -L "$EMB_LOG_DIR" ]; then
  rm -r "$EMB_LOG_DIR" || error_exit "Could not unlink $EMB_LOG_DIR"
  ln -s "$LOG_DIR" "$EMB_LOG_DIR" || error_exit "Could not link $EMB_LOG_DIR"
fi

# configuration
if [ ! -d "$CONFIG_DIR" ]; then
  mkdir -p "$CONFIG_DIR" || error_exit "Could not create $CONFIG_DIR"
  chmod 750 "$CONFIG_DIR" || error_exit "Could not change ownership of $CONFIG_DIR"
fi

if [ ! -e "$CONFIG_FILE" ] && [ ! -L "$EMB_CONFIG_FILE" ]; then
  cp "$EMB_CONFIG_FILE" "$CONFIG_FILE" || error_exit "Could not copy $EMB_CONFIG_FILE to $CONFIG_FILE"
  chmod 640 "$CONFIG_FILE" || error_exit "Could not change ownership of $CONFIG_FILE"

  # change defaults
  sed -i "s/port\: 3000/port\: ${DEFAULT_PORT}/g" "$CONFIG_FILE" || error_exit "Could not adapt $CONFIG_FILE"
  sed -i "s/backend\: dummy/backend\: ${DEFAULT_BACKEND}/g" "$CONFIG_FILE" || error_exit "Could not adapt $CONFIG_FILE"
  sed -i "s/schemas\.localhost/schemas\.$(hostname -f)/g" "$CONFIG_FILE" || error_exit "Could not adapt $CONFIG_FILE"
fi

if [ ! -L "$EMB_CONFIG_FILE" ] && [ -e "$CONFIG_FILE" ]; then
  rm "$EMB_CONFIG_FILE" || error_exit "Could not unlink $EMB_CONFIG_FILE"
  ln -s "$CONFIG_FILE" "$EMB_CONFIG_FILE" || error_exit "Could not link $CONFIG_FILE to $EMB_CONFIG_FILE"
fi

# systemd
if [ -d "$SYSD_DIR" ] && [ -d "$EMB_SYSD_DIR" ]; then
  for SD_FILE in "$EMB_SYSD_DIR/*" ; do
    ln -sf "$SD_FILE" "$SYSD_DIR/" || error_exit "Could not link $SD_FILE into $SYSD_DIR"
  done
fi

echo "Thank you for installing occi-server!"

exit 0
