#!/bin/bash
#
# Perform necessary occi-server removal steps
# after package is uninstalled.
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/occi-server
LINK_CONFIG_DIR=/etc/occi-server
LINK_DEST_DIR=/opt/rOCCI-server
LINK_LOG_DIR=/var/log/occi-server
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ -L "$LINK_CONFIG_DIR" ]; then
  rm $LINK_CONFIG_DIR || error_exit "Could not unlink $LINK_CONFIG_DIR"
fi

if [ -L "$LINK_LOG_DIR" ]; then
 rm $LINK_LOG_DIR || error_exit "Could not unlink $LINK_LOG_DIR"
fi

if [ -L "$LINK_DEST_DIR" ]; then
  rm $LINK_DEST_DIR || error_exit "Could not unlink $LINK_DEST_DIR"
fi

if [ -d "$DEST_DIR" ]; then
  ls $DEST_DIR/embedded/app/rOCCI-server/log/*.log > /dev/null 2>&1

  if [ "$?" -eq "0" ]; then
    mkdir -p $LINK_LOG_DIR || error_exit "Could not create a backup directory $LINK_LOG_DIR"
    cp -p $DEST_DIR/embedded/app/rOCCI-server/log/*.log $LINK_LOG_DIR || error_exit "Could not backup log files to $LINK_LOG_DIR"
  fi
fi

if [ -f "/etc/redhat-release" ]; then
  rm -rf $DEST_DIR || error_exit "Could not unlink $DEST_DIR"
else
  rmdir $DEST_DIR/runtime || /bin/true
  rmdir $DEST_DIR || /bin/true
fi

echo "occi-server has been uninstalled!"

exit 0
