#!/bin/bash
#
# Perform necessary occi-server setup steps
# after package is installed.
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
USAGE="usage: $0"

DEST_DIR="/opt/occi-server"
CONFIG_DIR="/etc/occi-server"
CONFIG_FILE="${CONFIG_DIR}/rocci_server.yml"
CONFIG_VARS="${CONFIG_DIR}/variables"
LOG_DIR="/var/log/occi-server"
SYSD_DIR="/etc/systemd/system"

EMB_DEST_DIR="${DEST_DIR}/embedded/app/rOCCI-server"
EMB_CONFIG_FILE="${EMB_DEST_DIR}/config/rocci_server.yml"
EMB_LOG_DIR="${EMB_DEST_DIR}/log"
EMB_SYSD_DIR="${EMB_DEST_DIR}/examples/systemd"
EMB_TMP_DIR="${EMB_DEST_DIR}/tmp"

DEFAULT_LOG_LEVEL="warn"
DEFAULT_BACKEND="opennebula"
DEFAULT_HOST="127.0.0.1"
DEFAULT_HOSTNAME=$(hostname -f)
DEFAULT_PORT=11443

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# user
id -u rocci > /dev/null 2>&1
if [ "$?" -ne "0" ]; then
  useradd --system --shell /bin/false rocci || error_exit "Could not create the rocci user account"
  usermod -L rocci || error_exit "Could not lock the rocci user account"
fi

# installation ownership
chown -R root:root "$DEST_DIR" || error_exit "Could not change ownership of $DEST_DIR"
chown -R rocci:rocci "$EMB_TMP_DIR" || error_exit "Could not change ownership of $EMB_TMP_DIR"

# logging
if [ ! -d "$LOG_DIR" ]; then
  mkdir -p "$LOG_DIR" || error_exit "Could not create $LOG_DIR"
  chown rocci:rocci "$LOG_DIR" || error_exit "Could not change ownership of $LOG_DIR"
fi

if [ ! -L "$EMB_LOG_DIR" ]; then
  rm -r "$EMB_LOG_DIR" || error_exit "Could not unlink $EMB_LOG_DIR"
  ln -s "$LOG_DIR" "$EMB_LOG_DIR" || error_exit "Could not link $EMB_LOG_DIR"
fi

# configuration
if [ ! -d "$CONFIG_DIR" ]; then
  mkdir -p "$CONFIG_DIR" || error_exit "Could not create $CONFIG_DIR"
  chmod 755 "$CONFIG_DIR" || error_exit "Could not change permissions on $CONFIG_DIR"
fi

if [ ! -e "$CONFIG_FILE" ] && [ ! -L "$EMB_CONFIG_FILE" ]; then
  cp "$EMB_CONFIG_FILE" "$CONFIG_FILE" || error_exit "Could not copy $EMB_CONFIG_FILE to $CONFIG_FILE"
  chown root:rocci "$CONFIG_FILE" || error_exit "Could not change ownership of $CONFIG_FILE"
  chmod 640 "$CONFIG_FILE" || error_exit "Could not change permissions on $CONFIG_FILE"
fi

if [ ! -L "$EMB_CONFIG_FILE" ] && [ -e "$CONFIG_FILE" ]; then
  rm "$EMB_CONFIG_FILE" || error_exit "Could not unlink $EMB_CONFIG_FILE"
  ln -s "$CONFIG_FILE" "$EMB_CONFIG_FILE" || error_exit "Could not link $CONFIG_FILE to $EMB_CONFIG_FILE"
fi

if [ ! -f "$CONFIG_VARS" ]; then
  cat > "$CONFIG_VARS" << EOF
export RAILS_ENV=production

export HOST=$DEFAULT_HOST
export PORT=$DEFAULT_PORT
export SECRET_KEY_BASE=$(head -c 69 /dev/urandom | base64 -w 0)
# export HOST_CERT=/path/to/cert
# export HOST_KEY=/path/to/key

export ROCCI_SERVER_LOG_LEVEL=$DEFAULT_LOG_LEVEL
export ROCCI_SERVER_HOSTNAME=$DEFAULT_HOSTNAME
export ROCCI_SERVER_PORT=$DEFAULT_PORT
export ROCCI_SERVER_KEYSTONE_URI=https://${DEFAULT_HOSTNAME}:5000/
# export ROCCI_SERVER_MEMCACHE=localhost:11211
export ROCCI_SERVER_BACKEND=$DEFAULT_BACKEND

# export ROCCI_SERVER_OPENNEBULA_ENDPOINT=http://localhost:2633/RPC2
# export ROCCI_SERVER_OPENNEBULA_TIMEOUT=30
export ROCCI_SERVER_OPENNEBULA_SCHEMA_NAMESPACE=http://schemas.${DEFAULT_HOSTNAME}/
# export ROCCI_SERVER_OPENNEBULA_TEMPLATE_DIR=

# export ROCCI_SERVER_ENCRYPTION_TOKEN_CIPHER=AES-128-CBC
# export ROCCI_SERVER_ENCRYPTION_TOKEN_KEY=$(head -c 69 /dev/urandom | base64 -w 0)
# export ROCCI_SERVER_ENCRYPTION_TOKEN_IV=$(head -c 69 /dev/urandom | base64 -w 0)
EOF

  chown root:rocci "$CONFIG_VARS" || error_exit "Could not change ownership of $CONFIG_VARS"
  chmod 640 "$CONFIG_VARS" || error_exit "Could not change permissions on $CONFIG_VARS"
fi

# systemd
if [ -d "$SYSD_DIR" ] && [ -d "$EMB_SYSD_DIR" ]; then
  for SD_FILE in ${EMB_SYSD_DIR}/* ; do
    if [ -f "$SD_FILE" ]; then
      ln -sf "$SD_FILE" "${SYSD_DIR}/" || error_exit "Could not link $SD_FILE into $SYSD_DIR"
    fi
  done
fi

echo "Thank you for installing occi-server!"

exit 0
